version: '3.8'

services:
  mariusli:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: hummelpage-frontend
    ports:
      - '3000:3000'
    networks:
      - shared-network

  zoebun:
    build:
      context: ../../zoebun
      dockerfile: Dockerfile
    restart: always
    container_name: zoebun-hummelpage
    ports:
      - '3001:3000'
    networks:
      - shared-network

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80' # Public Web Port
      - '4443:443' # Public SSL Port
      - '81:81' # Admin Panel Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - mariusli
      - zoebun
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
